### ISSUE TITLE
Rending Gale "Flight mode" broken

### ISSUE THREAD

**Issue by Alrawn** [P3pp3rF1y/Reliquary#107]
Flight Mode was working great in 1.9 but in 1.9.4, the charge indicator in the lower right corner flashes from the current number of charges to 0 while flying and flight is constantly turning on and off, so no more smooth flying.

**Comment by P3pp3rF1y** [comment]
In my tests this seems to be the case on dedicated server (in single player the number seems to always show the correct number). I think I know where the issue is and will look into it today so hopefully later today there will be a build with the fix available for download.

**Comment by Alrawn** [comment]
Sorry, I forgot to mention this was on forge-server 1.9.4

A fix would be great, since getting that heart of the storm was a real pain and the flight mode is great (esp. with elytra)

**Comment by P3pp3rF1y** [comment]
This is turning out to be more difficult than I thought it would be. It's also very different from what I thought the issue was. There was a recent change to forge that makes sense for other parts of the app, but broke syncing capabilities (the thing that I use to store charge) to client. Not completely but enough for rending gale to behave the way you observe it. I am trying to figure out what the fix is supposed to be in this case. May require a fix to forge as well.

**Comment by Alrawn** [comment]
I found a workaround for this, might be interesting for othes using reliquary until this is fixed. Setting the number of feathers consumed by flight mode to 0 via xreliquaryx.cfg (cast_charge_cost=0) stops the flight mode from stuttering on/off midair.

**Comment by P3pp3rF1y** [comment]
Yes that works, but that makes the flight so cheap. I will have a new build on CF shortly, am just in the middle of compiling a changelist so you should have a fix soon.

**Comment by P3pp3rF1y** [comment]
And this is now released, took quite a bit of time to get reviewed for some reason.
