### ISSUE TITLE
Interdiction Torches don't repel TCon slimes

### ISSUE THREAD

**Issue by Drullkus** [P3pp3rF1y/Reliquary#109]
Mod Filename - Reliquary-1.9.4-1.3.2.372.jar

Modpack - FTB Unstable 4.0.7

I'm unsure who's side this is, but TCon's Blue Slimes are not repelled by the Interdiction torches. I have tested and normal slimes are repelled by the interdiction torches.

**Comment by P3pp3rF1y** [comment]
So looks like tcon was added later on in the Unstable pack and blue slimes thus didn't get added to the list of entities that interdiction torch can push. Basically "tconstruct.blueslime" is missing in the interdiction_torch.entities_that_can_be_pushed config list. The solution is fairly simple just regenerate the config by deleting it or even just delete that section and all entities in the modpack will get added to the list.

I guess I could look into changing this from white list to black list in the future, this is the way it used to work as I didn't touch that logic.

BTW: did you get a witch hat when you logged on? 
because

```
    @SubscribeEvent
    public void blameDrullkus(PlayerEvent.PlayerLoggedInEvent event) {
        // Thanks for the Witch's Hat texture! Also, blame Drullkus for making me add this. :P
        if(event.player.getGameProfile().getName() == "Drullkus") {
            if(!event.player.getEntityData().hasKey("gift")) {
                if(event.player.inventory.addItemStackToInventory(new ItemStack(ModItems.witchHat))) {
                    event.player.getEntityData().setBoolean("gift", true);
                }
            }
        }
    }
```

**Comment by Drullkus** [comment]
Thanks for the concern! I didn't realize that code was still there... Haha

No I didn't get the hat! D:

**Comment by P3pp3rF1y** [comment]
ohh, just noticed what the issue with that was == instead of .equals. I have patched that so yeah you should get it next time you're playing with the next version of Reliquary :D

**Comment by Drullkus** [comment]
Woohoo! ❤️ Thanks :)

**Comment by P3pp3rF1y** [comment]
And a new version with the fix is now released so as soon as unstable updates you can enjoy your hat.
