### ISSUE TITLE
[1.10] Please return other mods integration!

### ISSUE THREAD

**Issue by mrapplexz** [P3pp3rF1y/Reliquary#116]
Minecraft 1.9.4 mods are fully compatible with Minecraft 1.10. Can you return other mods integration?

**Comment by P3pp3rF1y** [comment]
Well, not all 1.9.4 mods are fully compatible with 1.10, for example 1.9.4 reliquary wouldn't run on 1.10 because of some skeleton changes related to strays. But yes if there are changes they are minimal so I will try to readd these back and if the integrations will run I will get a new release out with integrations.

**Comment by P3pp3rF1y** [comment]
And they indeed seem to work properly so I will likely be releasing another release today.

**Comment by P3pp3rF1y** [comment]
This is now released on CF
