### ISSUE TITLE
Version 1.10-1.3.2.406 No Slime Pearls

### ISSUE THREAD

**Issue by SummitSummit** [P3pp3rF1y/Reliquary#123]
Playing the FTB Unstable modpack for MC 1.10 Magma cubes are not dropping slime pearls.  JEI says they will drop the 10% of the time on player kill but I have slain hundreds of magma cubes and not a single pearl has dropped.  I have a magnet so I'm not missing any drops.  I have stacks of magma creams but not one pearl.  I've killed them without looting (just to check) with my looting 3 sword and even my looting 4 sword (ancient tome score!) but no pearls.  Gonna go hunt down a swamp and try killing regular slimes, see if they drop any.

**Comment by P3pp3rF1y** [comment]
That is actually an issue with JER integration - magma cubes are not supposed to drop slime pearls, they only drop molten cores. And yes you should get slime pearls from slimes. I will see if I can already fix this, but anyway I am going to keep this issue open until I fix it so that JER stops displaying slime pearls for magma cubes

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of Reliquary (that I just uploaded) with the latest version of JER.
