### ISSUE TITLE
Rending Gale Bug

### ISSUE THREAD

**Issue by Traverse-Joe** [P3pp3rF1y/Reliquary#131]
so if you hold pull or push mode and double tap jump you can fly up slowly if you change items during the flight you get creative mode flight and you dont even need the rending gale to fly but it does wear off on logoff or death

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. After looking deeper into this there were two more cases that would allow players to gain creative flight - when rending gale got dropped while right click was held during flight mode and when player changed to another item (as in your case) while using flight mode.

All of these will be fixed in the next release.

**Comment by P3pp3rF1y** [comment]
Fixed in latest release

**Comment by Traverse-Joe** [comment]
Glad i could help
