### ISSUE TITLE
Suggestion: Adding a Cure zombie villager bullet

### ISSUE THREAD

**Issue by Kaisoul** [P3pp3rF1y/Reliquary#159]
I was wondering if there can be added a cure zombie villager bullet.   The normal cure method takes a while to procure and time to take affect...  i don't mind taking time to make a cure i just need a better delivery method then default minecraft.

**Comment by P3pp3rF1y** [comment]
I was thinking of creating Reliquary potion arrows similar to the ones in Vanilla just created with Reliquary potions and I will likely add them. 

But I could also make potion shots and add some kind of combine potion with golden apple method where you could use these to convert zombie villagers. I will see how well this is going to play out.

**Comment by Kaisoul** [comment]
thanks for the reply/info hope that the arrows & shots work out ^_^

**Comment by Twisted-Code** [comment]
I support this, and would like to add that you could implement some sort of "sliding scale of convenience vs. effectiveness". I.e. You could add 2 cures: one that costs about as much as a weakness potion and golden apple and is about as effective, and another that cost more but cures more quickly, possibly even instantaneously. Perhaps the latter could be more costly partly in that it counts as hurting a villager because damage could be dealt one tick after the villager is cured. Whatever the case though, I'm sure you'll work it out to be as well-balanced as the rest of the mod 😄.

**Comment by P3pp3rF1y** [comment]
In 1.11.2 I have added Cure potion effect, some new ingredients to potion map and also attached the effect to these and some of the preexisting ingredients. So you can get this using the same way as any other Reliquary potion. 
The cure potion effect will only start the conversion process for zombies that are under effect of weakness or weakness needs to be part of the same potion as cure (there are some combinations in potion map that can get you this).
btw: delete potion_map in your config to get this recreated with the new ingredients.
