### ISSUE TITLE
Unable to retrieve item from pedestal when something is equipped in offhand

### ISSUE THREAD

**Issue by bafomdad** [P3pp3rF1y/Reliquary#169]
Items can be retrieved from pedestal by shift+rightclicking. However, when main hand is empty and offhand is not, nothing happens. By unequipping anything from both hands, I am able to retrieve items that were placed on pedestals.

Version: 1.10.2-1.3.3.543.jar
Forge version: 1.10.2-12.18.1.2053

**Comment by P3pp3rF1y** [comment]
So this is likely something that I am not going to fix. 
The reason is how minecraft works, because in case of something in the off hand and player shift right clicking the pedestal it doesn't trigger the usual logic. 
So the only way I could fix this would be to hook into the event that gets triggered any time a player clicks on anything and in the there check if they are actually clicking on pedestal. That just seems a little too heavy handed to me for what it would be fixing.
So I will keep this around for a bit and will look into how bad it is to handle this case in the player click event, but don't be surprised if I just close this with "not going to fix" note.

**Comment by bafomdad** [comment]
I understand, it's not really something that bothers me too much.

But if you consider this as something that doesn't need to be fixed, instead of something that's explicitly by design, keep in mind that players are likely to always have something in the offhand slot, be it shields tools or whichever. The offhand system is pretty new, but it's there to stay.

**Comment by P3pp3rF1y** [comment]
This is resolved/implemented in the latest Reliquary release
