### ISSUE TITLE
Charms losing enchants when placed in charm belt

### ISSUE THREAD

**Issue by braingkk** [P3pp3rF1y/Reliquary#173]
Basically put, when placing enchanted charms in the charm belt, they seem to loose their enchants.

**Comment by P3pp3rF1y** [comment]
This is by design. What kind of enchantment are you putting on those anyway? unbreaking and mending shouldn't work and I am not aware of any other that would make sense when used with charm.

**Comment by braingkk** [comment]
I was using unbreaking enchant, anvil should not let the enchants apply tho if enchanting them is unintended, unless it has been changed in a later version, I am on 1.10.2-1.3.3.543, and had no problem putting unbreaking on with an anvil.

there are some enchants like "Unusing" [added by evilcraft] which makes you not use a tool once it hits 1 durability, would be very useful on the charms.

**Comment by P3pp3rF1y** [comment]
I checked and I am only explicitly not allowing mending to be applied, but unbreaking doesn't do anything on the charm as well. 
My thinking was why would you apply enchant to charm when it doesn't do anything. 

And regarding the evilcraft one that would require some implementation on my side as well so that the damage gets routed through usual damage events / methods and I am not sure that I want players not having to worry about charms breaking. That is part of the balance with the belt that you have to keep an eye on those if you're actually still killing the creatures. The main purpose of charms is that the mobs ignore you and not that you can attack them with no harm.

I have some thoughts on my mind to balance them even a little more towards that notion, but will see if I want to be that evil to players.

**Comment by braingkk** [comment]
generally people look on JEI, NEI or whatever the flavor of the month is to see possible enchants, and apply them just because they can. I know that is why i put it on in the 1st place. denying enchants would help limit confusion in the 1st place.
