### ISSUE TITLE
[1.7.10] Crash on joining Server.

### ISSUE THREAD

**Issue by MaxineBean** [P3pp3rF1y/Reliquary#175]
Hello, just to say, I do not know weather or not 1.7.10 is still supported but I figured I would post it anyways. 

So, I installed Reliquary on my server/pack and all clients connecting to my server would crash. 

Modlist, Yes reliquary is missing, but this was taken after the issue occurred: https://gist.github.com/MaDmaxwell311/605a0bd3ab2a2be0b13b1d11efc3cb56

Client log and crash: https://gist.github.com/MaDmaxwell311/ff4c928db6d2f6b1c78ba0dac4e2221b

Server log: https://gist.githubusercontent.com/MaDmaxwell311/986eea873c49d8fb981a3ebb169bb09e/raw/3df113a8ce565f0bfc60af7b7f0f04f5644f4570/Server.txt

Note: This was not an isolated issue, all clients on my server had this crash, not just me.

Note 2: The networking errors that occur when a client "connects" is the server throwing an error at the player's client crashing. This error has always occurred when a client connects and their client crashes, not just during this issue.

**Comment by P3pp3rF1y** [comment]
From what I can see Reliquary has nothing to do with this. First there's no mention of Reliquary in the stack traces. But it also crashes on handling a packet when the client joins. And Reliquary doesn't send any packets at that point, the only ones it sends are related to tile entities being placed in the world which obviously couldn't be the case. 
It may be some other mod sending this because of Reliquary being in the pack but I find that doubtful.

Sorry, can't help more with this.

**Comment by MaxineBean** [comment]
I figured it was a more obscure issue, if we added the mod the clients would crash if we removed it, clients would not crash and could join the server. However, this could just be a mod interaction issue.

**Comment by sanomi78** [comment]
@MaDmaxwell311 how did you solve this? I am having exactly the same issue, but when i remove Reliquary from the server the server will hang on startup!
