### ISSUE TITLE
tome of alkahestry dupes

### ISSUE THREAD

**Issue by clienthax** [P3pp3rF1y/Reliquary#176]
Seems both mods are blaming each other here
How can we resolve this?

https://github.com/P3pp3rF1y/Reliquary/issues/121
https://github.com/SleepyTrousers/EnderIO/issues/3551

**Comment by P3pp3rF1y** [comment]
This is resolved for quite some time already. The last one in the series was https://github.com/SleepyTrousers/EnderIO/issues/3675. Are you still getting any of these issues?

**Comment by clienthax** [comment]
@P3pp3rF1y 
We are running a 1.7.10 server
Reliquary version Reliquary-1.7.10-1.2.1.483.jar
EnderIO version EnderIO-1.7.10-2.3.0.429_beta.jar

Place down a enderio crafter, put in a diamond and a fully charged tome in the middle and a diamond under it in the crafting grid,
put a chest next to it and put in a diamond and the tome.

Charges on the tome are not consumed by the crafter.

**Comment by clienthax** [comment]
from what i can see, this patched it recently in 1.10.2~
https://github.com/P3pp3rF1y/Reliquary/commit/4d0cceaf44d343326606774890d4c21b415848ca
but not in the old versions

**Comment by P3pp3rF1y** [comment]
I didn't realize you mean the old 1.7.10 versions. I don't think those can even be fixed as the only thing that can be used in there to return items used in crafting is getContainerItem and that doesn't have any context of what recipe the Tome was used in - crafting/charging/uncharging. The way it was done there was through player only event, but that obviously doesn't run for machines. The only thing I could think of that can be done in there is change the code so that the tome gets deleted the first time it's used in machine. But honestly I am not releasing another version for 1.7.10. 
I am focusing on 1.10 now.

**Comment by clienthax** [comment]
@P3pp3rF1y
Would something like this work?
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv3-1.7.10/src/main/java/appeng/items/tools/quartz/ToolQuartzCuttingKnife.java

Just looking for fix for my server atm

**Comment by P3pp3rF1y** [comment]
No it wouldn't. Take a look at getContainerItem, they just damage the knife with one damage on craft. You could also use 1 redstone charge there but that would mean that it would use one charge whatever recipe it's used in - whether you're charging it, taking redstone out or duping things and however much charge should change in these cases. Basically the only way as I said to prevent dupe bug is to return null from the method and then auto crafters would just destroy the tome once used in a recipe for the first time. 

My suggestion if you want to prevent dupe bug is just turn off the tome in config.

**Comment by clienthax** [comment]
Oky, thanks for the info
