### ISSUE TITLE
BetterAgriculture mobs not affected by Reliquary

### ISSUE THREAD

**Issue by Discomanco** [P3pp3rF1y/Reliquary#181]
Mobs from BetterAgriculture are not affected by items such as Interdiction Torches and Rending Gale's Push/Pull functions.
https://github.com/MinecraftModDevelopment/BetterAgriculture/issues/26

**Comment by P3pp3rF1y** [comment]
Try to take a look at S:entities_that_can_be_pushed lists for both Rending Gale and Interdiction Torch. 
Do you see them listed in there? 

The config only gets these generated in once on creation and from that point on they need to be modified manually. So if you add the mod later on the entities from the mod wouldn't be in the list.

I may change this to blacklist rather than whitelist so that it behaves more like people expect it to - that is it works unless modpack author wants it to prevent from working for a specific case.

**Comment by Discomanco** [comment]
That would seem to be the case.
They appear in the comment, but not in the list itself.
Cheers for the notice

And I agree that a Blacklist would probably work better than a Whitelist

**Comment by P3pp3rF1y** [comment]
yeah and for that reason I will actually keep this open as a reminder to change it to blacklist
