### ISSUE TITLE
Coin of fortune in Baubles slot

### ISSUE THREAD

**Issue by StaticPH** [P3pp3rF1y/Reliquary#188]
While you have a coin of fortune in your amulet slot, every time you open the baubles GUI, either using the hotkey or the button in your inventory, it makes a dinging noise. This should only be happening when equipping the item in the slot. Activation state makes no difference.

To be clear, this ONLY happens if the coin of fortune is in the bauble slot. There is no dinging noise otherwise.

**Comment by P3pp3rF1y** [comment]
That looks like a Baubles bug. Basically this sound is played when the fortune coin is equipped. 
I just debugged that and apparently that "event" is now triggered every time a user opens baubles GUI, because it's triggered inside the method that fills in baubles slots with the items that the player has in there. So this is likely going to have some other side effects with other mods.
Not much that I can do with that apart from stopping the sound from playing altogether even when really equipped.

**Comment by StaticPH** [comment]
I don't know that anybody would complain if you did that, but I can understand that the bug isn't on your end. If you do something about it, you do, and if you don't, you don't. I personally don't really intend to put it in the bauble slot unless there is a way to deactivate it when its in there through some keypress or other, so its not really a concern for me. Just figured I should report seemingly unintended behavior when I saw it.
