### ISSUE TITLE
Coin of Fortune Suggestion

### ISSUE THREAD

**Issue by HyperspaceGamer** [P3pp3rF1y/Reliquary#197]
This feature may already be possible, but i haven't been able to find it, and I would love this feature. The feature that I am talking about is a blacklist for items that the Coin of Fortune will not try to pick up. When playing with the Coin of Fortune, I have to constantly disable it so that I don't pick certain items up, most notably the Applied Energistics 2 certus quartz/nether quartz/fluix crystal seeds, as they must be dropped in world to grow, which isn't possible when they are being sucked into my inventory by the Coin. I don't know if this suggested feature is even feasible, or if it may cause too much lag by always checking if an item that it attempts to pick up is on the blacklist, but I would love it if it is implemented.

**Comment by P3pp3rF1y** [comment]
I definitely feel like there should be a way to turn off coin of fortune, but need to figure out how. 

However there's currently no item in Reliquary that would allow filtering so that's not likely to happen. What I feel is probably better solution for now is a pedestal with turned off coin of fortune that will turn off all coins of fortune in a 9x9x9 area around it.

**Comment by HyperspaceGamer** [comment]
I actually like that idea a lot more. 
Maybe different areas would be nice to add in to that (an adjustable option on the single block or possibly different tiers of the block)? Also, when you say "turn off" the Coins of Fortune within that area, do you mean simply negating the effects of the coin, or physically disabling it? I ask, because if it is physically disabled, would it be automatically re-enabled upon leaving the area? And if so, how would leaving the area handle Coins that were manually disabled? 
Finally, since I'm pretty sure that the Coin works pretty differently from other magnets, I'm assuming that this block wouldn't work on other magnets? This feature is probably the least important to me, as the Coin is pretty much the only magnet item that I use, so I don't really need to worry about other magnets' compatibilities. 
Just some food for thought. 
If you do decide to add any of these features that you weren't previously, sorry about the extra workload...

**Comment by HyperspaceGamer** [comment]
I forgot this, but if you do add the pedastal feature, do you plan on making it so that any items within the area won't be sucked in by the Coin, or that only while within the area the Coin won't work? I ask because if standing 1 block outside of the radius, would it still suck in items, since the Coin is technically outside the radius, even though the items that it sucked up were inside of it?

**Comment by P3pp3rF1y** [comment]
That will likely be that items within the area couldn't be pulled out by the coin rather than coins not working within the area as that would do exactly what you mention, pretty much pull from everywhere, just avoiding one block. 

I have another suggestion for having coin not work near solegnolia. need to check how exactly that flower works but may use its logic to turn off at least the botania magnet.

Not sure about the area definitions. I always start thinking about using different kinds of blocks below pedestal for different effects but that just doesn't seem to be well thought through. So for now it's going to be 9x9x9.
