### ISSUE TITLE
Interdiction Torch and Grimoire of Gaia

### ISSUE THREAD

**Issue by ReportBot9009** [P3pp3rF1y/Reliquary#240]
Hello,

The Interdiction torch is not pushing mobs from the mod Grimoire of Gaia 3 in Minecraft 1.10.2.

**Comment by P3pp3rF1y** [comment]
This is very likely because the mod was added to the pack after the Reliquary config was generated. Currently it is designed to push only whitelisted entities and only when generating the config the first time it adds all entities to the whitelist. After the first time it uses the whitelist in config. I am going to change this to a blacklist, but in the meantime could you try regenerating Reliquary config (by deleting it) and see if the issue goes away?

**Comment by ReportBot9009** [comment]
Hello P3pp3rF1y,

That did the trick! Regenerating configs added all the mobs.

Thanks and take care
