### ISSUE TITLE
Emperor's chalice disappearing 

### ISSUE THREAD

**Issue by jellyfish23** [P3pp3rF1y/Reliquary#248]
After I've used it on a combustion engine from IC2 to fill it with water, the item just disappears? Have made multiple of them and has happened every time. It may work on separate items, will do more testing and report back.

Version: 1.8.9-1.3.1.296

**Comment by P3pp3rF1y** [comment]
Sorry I am no longer maintaining these old versions unless they have world breaking bugs in them. However based on this I have taken a look at 1.12 version of Reliquary and found some fixes that needed to be made and am pretty sure that your bug is caused by the fact that I didn't set a container item on emperor's chalice and thus the combustion engine thought that after using one bucket of water there isn't supposed to be any item returned anymore.
