### ISSUE TITLE
[1.12] Crash when loading

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#251]
Like the title says; [log here](https://pastebin.com/1t98ZgGC).

**Comment by P3pp3rF1y** [comment]
Did you modify alkahestry crafting recipes or perhaps have some mod that removes some vanilla items? Because this is kind of message one would get when either a recipe is defined that doesn't have any ingredients or when a vanilla item was removed that is defined as a crafting ingredient in one of the alkahestry recipes. 
Actually the second case I will put something in for to prevent the game from crashing, but still odd that any of those default items would be removed.

**Comment by ghost** [comment]
I checked to make sure, but no. I am still in the process of composing this modpack and have not touched any recipes yet. It must be one of the other mods that remove/change an item?

**Comment by P3pp3rF1y** [comment]
Probably, you have the modpack somewhere where I can get it to try? If a mod actually removes one of the default alkahestry crafting items I would guess that's going to break way more than just Reliquary because they are all very commonly used in recipes.

**Comment by P3pp3rF1y** [comment]
Actually, relooking the code and it's for sure not the ingredient missing, but rather seems like one of the ore dictionary items is the issue here. Looks like there is ore dictionary entry for copper/silver/steel/tin ingot, but at the same time there is no actual ingot assigned to this entry and my logic there only checks for existence of the ore dictionary entry.
I have changed that in dev to actually pull all entries assigned and see if there's at least one before loading recipe.

**Comment by ghost** [comment]
I don't have the modpack published anywhere, but I could export it from MultiMC if you want?

**Comment by P3pp3rF1y** [comment]
Actually let me send you pointer to dev build where I should have fixed this once it is built on bintray.

**Comment by ghost** [comment]
Ok, but I won't be able to test today, have to leave in a minute.

**Comment by P3pp3rF1y** [comment]
Sure, when you have time. 
here's the link https://bintray.com/p3pp3rf1y/maven/download_file?file_path=Reliquary-1.12-1.3.4.709unstable.jar

**Comment by RealGrep** [comment]
I had the same exact crash during startup. This test version, on the other hand, starts up fine for me. Can't (yet) say if there's anything else broken once I get into it, but it starts.

In case you want to replicate it, it's a very small and simple pack. Here's a listing of the mods used:
https://pastebin.com/S91SRpsW

This is on MC 1.12 and Forge 2443. It's mostly quality of life mods, a couple of niceties to help with storage and such, TCon and IE. I also tested it to see if it starts on 1.12.1, and it did.

**Comment by Lothrazar** [comment]
I have the same issue.  I downloaded the mod and thats it, no config files touched.  crafttweaker not installed or anything

java.lang.ArrayIndexOutOfBoundsException: 0
	at xreliquary.crafting.factories.AlkahestryCraftingRecipeFactory.parse(AlkahestryCraftingRecipeFactory.java:48)
at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:408)

**Comment by ghost** [comment]
Tested the dev build and that has solved this issue :-)  played for about an hour with it and no other issues cropped up so far.

**Comment by P3pp3rF1y** [comment]
This is now fixed in the latest release on curseforge so just go and grab it there.
