### ISSUE TITLE
All types of loaded magazines are not craftable. 

### ISSUE THREAD

**Issue by mahilo3550** [P3pp3rF1y/Reliquary#255]
Placing the correct recipe into a crafting table or via JEI (which, by the way, shows no loaded magazine possibility for any shot without a potion effect added to it. Even when you apply a potion effect to the shots the recipe will automatically go into the crafting table like it should, but without any output from it. So bummed... Spent all that time with this mod solely to use the handguns and I can't. Thanks.

**Comment by P3pp3rF1y** [comment]
What mc and mod version is that? And what mod pack?

**Comment by mahilo3550** [comment]
1.12 & 1.3.4.710

**Comment by mahilo3550** [comment]
No "mod pack". My own... about 175 different mods. But none of those have anything to do with why there's no loaded magazine for any/all bullets that don't have a potion affect applied to them later or even those aren't capable of being crafted

**Comment by P3pp3rF1y** [comment]
So I can craft all types with or without potions with that version, but the JEI recipe is wrong because it shows the empty magazine at the top left corner while it should be in the center surrounded with bullets. 
I will keep this open to fix that issue, but you should be able to craft them all by simply putting the empty magazine in the center. If not then it's likely one of the mods doing something with crafting that prevents the magazine recipe from working and there's nothing I can do about that.

**Comment by mahilo3550** [comment]
That's why then. How was I suppose to know the mag goes in the middle if the recipe is wrong?  Out of all my mods I've never seen that before. You're welcome.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release
