### ISSUE TITLE
Add Guide API book

### ISSUE THREAD

**Issue by P3pp3rF1y** [P3pp3rF1y/Reliquary#26]

**Comment by MCYayes** [comment]
Much of this mod looks awesome!
Some of it I've even figured out how to use!
The rest is useless unless I can use it. Without a guide book that tells me how to use things (like getting the handgun to actually fire once it's made and loaded with ammo), I can't have much fun with the mod.

If I understood how to use more of the things in this mod I'd make the Guide API users manual for it myself (as that's the kind of project I like doing)... Alas, I am clueless about 70% of the things in the mod and how they work.

**Comment by P3pp3rF1y** [comment]
I would definitely love if someone had time to work on a guide book that could be used in game. 
There is already content on https://github.com/P3pp3rF1y/Reliquary/wiki as well as in JEI descriptions in game and I am happy to answer any additional questions and/or update this content to include more info where needed.

**Comment by MCYayes** [comment]
I'm on Discord. if you are as well, then perhaps we can work together where I can work on figuring out all the issues and stuff and be able to easily ask you any questions I have without filling up your github comments (unless you prefer to communicate here).

Let me know what you think, but if you're willing to answer the questions I come up with, I'm willing to work on putting together an in-game guide for the mod. 

I may also have some suggestions (like a config setting that will let me tailor how many items a Void Tear will keep in my inventory, or making the Void Tear search whatever inventory it is in for items it stores instead of just players inventory - as this would be VERY useful since I use the Backpacks! mod (1.11.2), and the Void Tear doesn't gather things from within the backpack.)

Anyhow... Let me know what you think of the idea, and I'll see what I can do about making an in-game guide for the mod :)

**Comment by P3pp3rF1y** [comment]
Sure you can reach me on discord at https://discord.gg/Bft6WTQ . Not a very active place, but we can use it for the discussion or just to connect and PM from there.

**Comment by MCYayes** [comment]
I joined there... Not keen on how it wont let me change my nickname to my
minecraft name, but it's fine I guess.
The name I use there is mainly because of this email addy (which was named
from a RPG character I once played LONG ago.. :P )

Anyhow, I'm not super active on Discord either, but it works as a nice
communication medium for projects.
Cheers my friend!
~Yayes

*~Shadow VanDusen*
*Prince.Demitri@gmail.com <Prince.Demitri@gmail.com>*
