### ISSUE TITLE
NPE in console looking at a Reliquary Pedestal

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/Reliquary#263]
https://github.com/TehNut/HWYLA/issues/97#issuecomment-342232566

**Comment by P3pp3rF1y** [comment]
So actually the issue here is that when there's nothing that holds fluid in pedestal the pedestal returns null when it's asked for tank properties. That obviously isn't correct and is something I have already fixed in 1.12, but I am wondering how critical this is to you if it's just in server logs. Is it filling those significantly?
I could potentially do a blind merge of the 1.12 fix into 1.10 without much fixing and release a build with that for you if it's pressing. Otherwise I want to focus on 1.12 and the other mods I work on.

**Comment by ProsperCraft** [comment]
Just keep your focus on 1.12 :) Thank you for looking at it.
