### ISSUE TITLE
Lilypad of Fertility Dupe Bug

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#265]
I write the bug in Modern Skyblock 2 Modepack:

https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/398

The video: https://pudding.tk/RJu-h3PK.mp4

i dont need more to say?!

**Comment by P3pp3rF1y** [comment]
You didn't which version of mc / Reliquary that is for, but I assume that was for 1.12 using the latest version of Reliquary. And I have just retested in that version and can't see what you get there, so very likely some other mod causing this issue. 
If you will be able to recreate with just Reliquary feel free to reopen the issue here.
