### ISSUE TITLE
[1.12.2] Crash

### ISSUE THREAD

**Issue by PokeMaserJ** [P3pp3rF1y/Reliquary#267]
When Curing a Zombie Villager with a Cure potion after you throw a weakness potion onto it, you crash to desktop.
 https://pastebin.com/zjjN81Qm
Not sure if it effects the server, this was done in Single player
Reliquary 1.12.2-1.3.4.719
Forge 14.23.0.2550

**Comment by ArMoReDfUrY** [comment]
are you able to craft shots for the hunters handgun in that forge version? 
they don't show up in JEI for me and i can't craft them at all even though i know the recipes and confirmed them on the wiki.
i'm just not sure if it's a conflict or if the changes to shaped/unshaped crafting in forge2546+
i am using 2550 currently.

**EDIT:** it looks like it's just not showing in JEI and the wiki is out of date, i was able to find the recipe buy drilling down through the gun recipe to find the mag then the shots showed up from there.
but it would still be handy to see the mag recipe, it would make it a little better to find the shots.

**Comment by P3pp3rF1y** [comment]
@ArMoReDfUrY first of all, please create a separate issue for what you're trying to fix, because this one is for a crash with cure potion. 
And second I can see all magazines and shots fine in JEI and they all show their recipes as well in there. There was an issue previously with magazine recipes but that was fixed almost 2 months ago so make sure that you're using the latest 1.12 release. If you still can see the issue please describe in the new issue how exactly this can be recreated.
