### ISSUE TITLE
[Request] Mod support for mob drops

### ISSUE THREAD

**Issue by Shahelion** [P3pp3rF1y/Reliquary#276]
Slime Pearl:
Tinkers Construct slimes
Twilight Forest slime beetles

Lycanite's Mobs: (Not suggesting ALL listed mobs drop the specified item, just that those are good candidates) 

Zombie Heart:
-Ghoul Zombie
-Crypt Zombie
-Geist

Molten Core:
-Ignibus Drake
-Afrit
-Lobber

Bat Wing:
-Epion
-Remobra
-Manticore

Frozen Core:
-Wendigo
-Arix
-Serpix

Chelicerae:
-Lurker
-Eyewig
-Calpod
-Tarantula

**Comment by Not-February** [comment]
I think it'd be more viable to have a config of some kind to control which mobs drop what ingredient. I have noticed that if a mob-added mod inherits the loot pool from a vanilla mob which drops a Reliquary ingredient, that mob-added mod seems to drop the Reliquary ingredient as well. For completely new mobs, though, something like this would be a godsend.

Configurable control would be ideal for this in my opinion - since there are quite a few mods which add mobs in some way, and if it were configurable on a per-pack/user basis, people could just change or add what they need to happen.

In the meantime, there are probably other mods available which allow you to customize what a mob drops on an individual basis.

If you're on 1.12.2, you could try the following for adding your own mob drops to things(found via a quick CurseForge search):

https://minecraft.curseforge.com/projects/knob-control -> seems to have many modular functions, including mob drops
https://minecraft.curseforge.com/projects/mob-drops -> a simple utility that handles mob drops specifically
https://minecraft.curseforge.com/projects/in-control -> probably has a higher learning curve, but you can do a lot with it, like weird specific conditions for a certain kind of item to drop.

Disclaimer: I have not actually used any of these other than In Control at any point in time, so your mileage may vary.

**Comment by Shahelion** [comment]
Either way, how do you even find out what entity name to use for configs? Every mod seems to be different.

**Comment by Not-February** [comment]
If you have CraftTweaker 2 installed, you can run the following command and then check the crafttweaker.log file for a list of all currently registered entities in your game.

`/ct entities`

**Comment by P3pp3rF1y** [comment]
closing this as it seems primarily related to mobs that may drop just pure reliquary ones and as said there are other mods that can be used for that.
