### ISSUE TITLE
Client issue when trying to connect to a server with mysticalworld disabled.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/Reliquary#347]
https://github.com/EpicSquid/MysticalWorld/issues/3

**Comment by P3pp3rF1y** [comment]
This issue happens because Reliquary silver ingot crafting recipe produces silver ingot that is registered in ore dictionary and it fails during client / server handshake I am pretty sure because the same item isn't registered on the server if you don't have the other mod there. So the fix is simple, just put the mod on the server. There's no way Reliquary can fix this as it would require knowing if the item will be present on the server during the game load that is before you have even selected which server you want to connect to.

**Comment by ProsperCraft** [comment]
Right, but... Reliquary is on the server.

**Comment by P3pp3rF1y** [comment]
What I mean is that MysticalWorld is present on client and not on the server and because of that it has got silver ingot registered in the ore dictionary on client which Reliquary automatically uses for a result of alkahestry tome silver duplication (uses this one because it's the first one in the list of oredicted silver ingots). and as the same silver ingot doesn't exist on the server the handshake fails. So it's not Reliquary issue. if you remove mystical world from client as well or add it on the server you will have your issue solved. One thing that's odd to me though is how you are even able to connect to server when the mod is missing there, I would think forge would just reject this even before trying to connect and show it as such in the list of servers.

**Comment by ProsperCraft** [comment]
It is very common for mods to be disabled serverside, and clients with the disabled mod active to be able to connect.

**Comment by P3pp3rF1y** [comment]
That's certainly the first time I am hearing about that after 5 years playing and modding. But anyway there's no way I can "fix" this issue other than by removing functionality from Reliquary - basically stop supporting all alkahestry tome recipes with ore dictionary input/output as well as I wouldn't be able to determine if any other recipes would break if people have provided custom ones with non reliquary modded outputs because I wouldn't be able to tell if those mods will live on server when players try to connect to them.
