### ISSUE TITLE
Strange bug which needs to have this mod ruled out as the culprit

### ISSUE THREAD

**Issue by Sunconure11** [P3pp3rF1y/Reliquary#361]
https://github.com/Sunconure11/compitum-magia-issues/issues/10

**Comment by P3pp3rF1y** [comment]
Something is messing up the registered items and seems like it's removing them. Reliquary doesn't do anything with registered items.
My suggestion - rather than trying to work with all the mods that report the similar issue while removing the mods one by one try to remove more until it stops and then start adding mods back. I would start with all of the coremods as they are the most likely to cause something like this.
