### ISSUE TITLE
[1.15.2] Something is seriously amiss with the Lantern of Paranoia's placement logic.

### ISSUE THREAD

**Issue by thecanidcoder** [P3pp3rF1y/Reliquary#411]
Before:

![image](https://user-images.githubusercontent.com/22875626/79366396-1ff13480-7f1a-11ea-8cc1-ac8007a342cf.png)

After moving into the middle of the area and activating the Lantern: 

![image](https://user-images.githubusercontent.com/22875626/79366448-35fef500-7f1a-11ea-8e16-22bda2fcac4a.png)

Here's an example GIF of the lantern going crazy while mining:

https://gfycat.com/greencoordinatedkatydid

**Comment by P3pp3rF1y** [comment]
So the only thing i can say about that is that you have a mod that causes the light detection code to not work correctly because in my tests I never see torch double placements anywhere.

**Comment by thecanidcoder** [comment]
Good call. I had completely forgotten that I had added a mod ( https://www.curseforge.com/minecraft/mc-mods/phosphor-forge ) in a desperate attempt to reduce the constant stuttering I get from lighting updates. Removing that seemed to correct my issues with the Lantern, although I _did_ notice the situation shown in that GIF still occurs when mining with Quark's Pickarang. 


Otherwise, it immediately seems better.

**Comment by noobanidus** [comment]
If Phosphor is deferring some of the lighting updates, it's possible that it's placing torches too fast before the calculations have been properly updated? I'm not entirely sure, but I know the phosphor developer so I can have a chat to them about what might be going on.

EDIT: I've noticed, especially with Ore Excavate, this pattern of torch placement *without* Phosphor on 1.14.4, when blocks are broken torches can be immediately placed next to each other. My theory for this is that the light calculation has been cached for that block, so when the Lantern checks the lighting there it sees it as "dark" (because it was a fully opaque block) and places a torch.

**Comment by P3pp3rF1y** [comment]
That is possible, but I don't think I can determine that the light has been cached. Possibly could force light calculations to happen but I am sure that would cause quite a bit of performance drop. 

Basically lantern calls world.getLightFor(LightType.BLOCK, pos) and if it sees light at or below the level in settings it places torch so if something is caching the value there or affects how that method works it could place the torches in incorrect places because lantern basically got incorrect info about lighting.

**Comment by noobanidus** [comment]
Perhaps just adding a delay so that it doesn't place torches as frequently? That might give the world time to catch up/uncache values.

**Comment by Shados** [comment]
I'm seeing this same issue on 1.16.4, without Phosphor. Adding a delay/interval between torch placements does seem like a simple work-around; it obviously wouldn't be perfect, but it would likely make this much less of an issue.

**Comment by thecanidcoder** [comment]
This is a closed issue. I would recommend opening a new one, referencing this issue if need be.
