### ISSUE TITLE
Less items from mobs

### ISSUE THREAD

**Issue by MechWarrior99** [P3pp3rF1y/Reliquary#43]
I was wondering if you could make it so Reliquary has less/no items that drop from mobs. While it is sort of fun to get them. later in game it is not vary 'mod friendly' when you have mob farms becasue you will get a bunch of the drops from Reliquary which are normally useless at that point in game. And early game they just take up inventory space.

**Comment by P3pp3rF1y** [comment]
Some of the feedback that I have seen is actually that the drops are not frequent enough. Which kind of blocks people from really enjoying the mod. 
I understand that in late game if you have all the items you need these are not worth anything but don't see a good way to reducing the drops or not making them drop these.
In terms of mob grinders you will always have a lot of something that you don't need so it should be matter of just void upgrades or sending to trash in my opinion. And early game you can just throw them away, they actually don't drop that much that they would clutter the inventory alone (in most cases you have 25% chance to get one per mob with Looting III)

However if you have ideas on how to achieve less/no drops late game let me know.
The only thing that comes to my mind for no drops late game is Blood Magic like weapon that would be used to get any, but in that case early game players wouldn't start playing the mod unless they knew they have to craft it to get the drops.

**Comment by MechWarrior99** [comment]
If you are really trying to get in to the mod they don't drop that much. But a lot of the things in Reliquary are one time craft only. You don't need more than one of most of the things in Reliquary. 
The way the recipes are right now there is almost nothing for early game. I could only find one or two things you could craft with out having to go to the nether or having to kill several Endermen.

I can think of a couple of ways of going about the drops. Have a weapon that you have to kill the mob with in order to get the item, maybe have it be a higher chance of dropping an item than it is right now. Have a splash potion that you throw at mobs then kill them with any weapon to get drops. Just remove drops, and craft the parts instead, maybe some kind of custom crafting mechanic. 

Those are the ideas I had. I don't know how you feel about them. Also you may want to look in to making some of the recipes cheaper or more friendly for earlier game?

**Comment by P3pp3rF1y** [comment]
So in terms of the mob drops what I am thinking is that I will actually make them part of crafting recipes 
- Rib bone > bone meal
- Skeleton skull + some withered ribs > wither skelly skull
...

In terms of how hard the recipes are - they actually are set to easy crafting recipes currently so easier than in 1.7 (hard mode was the default there). So I will wait for more feedback before changing the recipes either way.

**Comment by Febilian** [comment]
I was definitely noticing that the recipes are easier than they were in 1.7. Personally, I kind of miss the recipes being more difficult, it gave more of a sense of accomplishment when you finally made that special item. Also, as it stands, there's almost no reason to actually try to get Eyes of the Storm since I remember one of the main reasons I tried in older versions being the Tome of Alkahestry(because it took all the difficult-to-get drops), and now it's much easier to craft in comparison. Considering how powerful the tome is(you can duplicate nether stars, for example), I'd at least turn that recipe into a more difficult one again.

**Comment by P3pp3rF1y** [comment]
Yeah, that recipe definitely seems way too easy to me. Goes on my list to tweak for final version.
I will also likely review the base alkahestry recipes as 128 redstone for nether start doesn't sound right (Even though you of course have to have that first one so maybe not that bad)
Also eye of the storm is something I want to take a look at as I don't see a reliable way to get that in vanilla. Basically it's luck based unless I am missing anything. There are 2 items in Reliquary that allow you to charge creepers but they both require the eye to craft so that's not going to help. Perhaps I will make a different recipe for storm shots and let players charge creepers that way.

**Comment by Febilian** [comment]
Yeah, in vanilla it's ridiculously hard to get an eye of the storm, but it's also important to remember that a lot of times, other mods add ways to supercharge creepers in some way or another by choosing where lightning strikes land somehow. I guess it depends on whether you want to balance the mod around usage in modpacks or as a standalone experience.

**Comment by P3pp3rF1y** [comment]
So I am now doing multiple things for this one:
1. TC aspects on mob drops
2. Uncrafting recipes for almost all drops (but bat wings, which I couldn't think of realistic recipe and likely this one is the least of an issue in terms of inventory clutter)
3. eye of the storm now can be achieved through storm shots as those now require 2 creeper gland instead of eye of the storm
4. tome of alkahestry is now on hard by default
5. nether star duplication now costs 4 stacks of redstone by default

Closing this as done
