### ISSUE TITLE
NPE with reliquary-1.16.3-1.3.4.1042.jar

### ISSUE THREAD

**Issue by Letoric** [P3pp3rF1y/Reliquary#462]
Initial (looping) crash
https://pastebin.com/Y8GQDErH

Crash Report:
https://pastebin.com/BQU5kwLG

Reverting to the 1039 build made the crash stop occurring.

**Comment by P3pp3rF1y** [comment]
The only thing I can gather from this is that likely the elemental craft entity doesn't have attributes initialized when it gets created or that there's some core mod (and there's plenty in your pack) that changes how attributes work that causes this crash, but it basically crashes when the entity tries to get its max health which in default vanilla implementation can't crash like this.
I am pretty sure I can't do anything about this crash apart from removing functionality from Reliquary, but this really needs to be fixed somewhere else.
Going to leave this open for a bit just in case something comes up that would point to a possible issue in Reliquary.

**Comment by Letoric** [comment]
Same thing on this most recent update, reverting to 1039 build makes the crash stop occurring.


Crash Report:
https://pastebin.com/vVB2UdiS

**Comment by Sirttas** [comment]
I would like to understand because the entity causing the crash isn't supposed to be summoned.

**Comment by P3pp3rF1y** [comment]
The reason I create the entity is because I am figuring out if it's a boss or not and there's no place this can be found without having the actual entity. And honestly if any entity has its factory registered I would expect that the given factory can be called without crashes. Unless there's a good reason that I am missing. 
I can see that this was fixed in elemental craft so I am going to close. If I run into this in the future again I may add exception handling and log errors for entities like this instead of crashing but that obviously slows down the code unnecessarily.
