### ISSUE TITLE
crash when using handgun on server

### ISSUE THREAD

**Issue by Warbringer12** [P3pp3rF1y/Reliquary#468]
[crash-2020-10-30_00.15.56-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/5463138/crash-2020-10-30_00.15.56-server.txt)

**Comment by P3pp3rF1y** [comment]
Well the handgun was shot but then a whole lot of vanilla code that's modified by core mods was called and it ended up crashing  in ice and fire mod. And I don't see anything in their code that could have incorrectly originated in Reliquary. So you will need to report your issue to ice and fire, but it's pretty likely one of the core mods is actually the cause of the issue here.
