### ISSUE TITLE
[1.16.3] Server crashed, something about spawn egg?

### ISSUE THREAD

**Issue by Gbergz** [P3pp3rF1y/Reliquary#474]
Title^

**Minecraft:** 1.16.3
**Forge:** 34.1.42
**Reliquary:** 1.3.4.1051

**Crash-Report:** https://hatebin.com/aoqusbzlub

**Comment by P3pp3rF1y** [comment]
This is very odd, it complains about missing a method that has been on ItemSpawnEgg since 1.14.4 and is still there in 1.16.4. We also run with this on forgecraft with new versions of forge and never got this exception. So I can only speculate you have a core mod in your modpack that removes the method. If you can narrow it down to which mod causes it let me know.

**Comment by ViRb3** [comment]
This looks to be the same issue as #478. Check below for another report of the same issue, with the ATM6 modpack.

**Comment by ViRb3** [comment]
Thank you @P3pp3rF1y!
