### ISSUE TITLE
[Feature Request] Option to turn off spawn egg recipes + charm fragment drops

### ISSUE THREAD

**Issue by faeldray** [P3pp3rF1y/Reliquary#501]
As I have other mods that I would rather players use to create spawn eggs, it would be great to turn off the spawn egg recipes in the config.

Also, since a lot of the charm fragments from other mods' mobs don't have crafting recipes, maybe a solution to that would be to have an option to have them drop from those mobs, a percentage that could be set in the config.

**Comment by P3pp3rF1y** [comment]
The fragments are actually supposed drop from those mobs, just with very low chance. And now that I was looking at making this configurable I realized there was an issue in formula where it got multiplied by a very low number and thus they would almost never drop. 

Anyway that is now fixed in dev and new settings are in to be able to set the base chance and additional chance per looting level.

**Comment by P3pp3rF1y** [comment]
And yeah the setting to disable spawn eggs is also implemented.

**Comment by skerit** [comment]
It would be great to have a bit more documentation on fragments! I'm playing FTB Endeavour atm, and because some fragments have recipes and some don't it feels like those that don't are broken. (I really wanted a ton of zombie villager fragments 😅)

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge as for those fragments those that don't have recipes will drop directly from mobs with low chance, I will look into adding a bit of documentation somewhere about it.

**Comment by faeldray** [comment]
Much appreciated, thank you!
