### ISSUE TITLE
Void Tear Duplication Bug

### ISSUE THREAD

**Issue by Urbancase** [P3pp3rF1y/Reliquary#502]
If a named item is absorbed using a void tear and an unnamed version of the same item exists in the inventory, the void tear counts the amount of both item, but only absorbs the named items, resulting in duplication of the items. I am playing on the 1.12.2 version of the mod.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. I have the issue fixed in my 1.16.5 dev version. Unfortunately I don't really have time to continue maintaining 1.12.2 ,this issue doesn't seem that critical and that version has been out there for a very long time without anyone noticing so it will only be fixed in 1.16.5.

**Comment by Nicholas-Leppert** [comment]
Just thought I'd mention this issue is also noticeable with other void tear consisting items, in particular the Harvest Rod (Not really a problem if this is the only mod, major problem if Mystical Agriculture is added with diamond growing).  This was noticed 4/8/2021, with the current 16.5 posted version on curseforge.

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest release on curseforge, should cover even other items as well as the same functionality was used there to drain player's inventory.

**Comment by Hydraheads** [comment]
Someone on my server found this out, and I had to ban the item, and cease the means of acquiring it.  I know you want to focus on the latest versions, but we really need a fix here in 1.12.  This can be an economy destroyer if people who figure it out hit other servers, via diamond blocks and even things like opinium cores. The sky is the limit.
