### ISSUE TITLE
LanternOfParanoia appears to invoke ServerHangWatchdog on server while client in Mekanism Digital Miner UI

### ISSUE THREAD

**Issue by miiichael** [P3pp3rF1y/Reliquary#507]
Survival server. Lantern in inventory and activated, but torches in off-hand (it was being a bit too enthusiastic with spraying torches everywhere while I was underwater). Server crashes do not occur when the lantern is deactivated.

Here, have a couple of [crash](https://github.com/P3pp3rF1y/Reliquary/files/6215284/crash-2021-03-27_14.34.24-server.txt) [reports](https://github.com/P3pp3rF1y/Reliquary/files/6215285/crash-2021-03-27_13.58.52-server.txt).

Even if there turns out to be a Mekanism bug somewhere, it's probably a good idea for the lantern to not crash the server as a result. :)

**Comment by P3pp3rF1y** [comment]
To be honest not sure what took so long for you or it may have just got to processing lantern of paranoia code when it crashed because in my performance testing the code where it crashed is pretty much untrackable because of how little time it takes even when summarized over tens of seconds of gameplay.
Anyway I made a change to lantern that will make it pause for a bit after each placement and for a bit longer time if it wasn't able to place anything so it should decrease the load on server.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
