### ISSUE TITLE
mobdrops

### ISSUE THREAD

**Issue by bartjeman11** [P3pp3rF1y/Reliquary#508]
all the special drops like slime pearls and hearts are not dropping i cant find a way to resolve this i have a custom made modpack witha few friends on my server

**Comment by P3pp3rF1y** [comment]
Given that I know that they drop correctly both in dev environment and in various modpacks the only thought would be that you have turned off mob drops in config or that you have some other mod that affects the drops. And without at least info on what mod that is that's causing you these issues there's nothing I can do. But check the config first to make sure that you don't have mob drops turned off.

**Comment by bartjeman11** [comment]
okay could i send you a link to my modlist on google drive?

**Comment by P3pp3rF1y** [comment]
I don't really have time to debug your modpack to figure out what mod is causing this. I guess I could take a quick look at the list if something may be jumping out at me, but I don't recall any mod causing this kind of issue so probably won't be able to tell you much

**Comment by bartjeman11** [comment]
okay i cant find the config in my ftp but heres the link its only a few mods
https://drive.google.com/drive/folders/10Fb6Cnp25wWQWUN7HoVb4vSAgkQOmyaX?usp=sharing

**Comment by bartjeman11** [comment]
there seems to be no config at all for reliquery in my server

**Comment by bartjeman11** [comment]
![image](https://user-images.githubusercontent.com/46538849/112724131-10dc7a00-8f12-11eb-8a46-5f4fe4ec5f52.png)

**Comment by bartjeman11** [comment]
every datapack/mod on my server

**Comment by P3pp3rF1y** [comment]
xreliquary-common.toml is the name of the config file, you need to be looking for it in config folder
And from the list you posted it looks like collective may be causing your issue. at least from what I gathered from quick description it seems to be caching what drops a mob can drop and it's possible that due to them being rarer the reliquary drops don't get cached and thus are not dropped later on. Try running your modpack without it and mods that depend on that library as well and see if it helps - should be easy to test in creative - just give yourself sword with high looting level and you should get reliquary drops soon.

**Comment by bartjeman11** [comment]
ill try

**Comment by bartjeman11** [comment]
this was the problem

**Comment by bartjeman11** [comment]
it was the datapack anti creeper grief

**Comment by P3pp3rF1y** [comment]
alright, closing this then
