### ISSUE TITLE
Suggestion: override attribute modifiers for magicbane

### ISSUE THREAD

**Issue by Jackiecrazy** [P3pp3rF1y/Reliquary#535]
At the present it is not entirely obvious how much damage magicbane deals in a hit. By overriding attribute modifiers (there is a stack-sensitive version to my knowledge), the attack damage will be displayed on the tooltip. This will make it easier to work with for mods/datapacks that test for the attack damage attribute, as well as be easier to read in general.

**Comment by Darkmega18** [comment]
O-hey Jackie.

P3pp3rf1y: Since this is about magicbane:
A config to set a maximum damage, or to set how much damage is gained per enchantment level would be good also. as some packs just go bouncing off the walls with power creep sometimes and so you can just keep slapping every enchant under the sun on it and it becomes a very powerful weapon. True to form, but with a bit of work, almost gamebreakingly.

I know some mods also have like, variable sprites for some of their items states etc. A visual thing to make it cool would be to give it a gradually thickening yellow aura around the magicbane's sprite as it gets more and more powerful up to said hypothetical maximum damage limit I'm suggesting. Or an aura and maybe it becomes more ornate and sword like, where when it starts it was just a kinda ornate looking dagger at first.

**Comment by Jackiecrazy** [comment]
![2021-11-24_03 10 42](https://user-images.githubusercontent.com/6895485/143324163-442c59fe-e3aa-4943-8e66-3125494e38d1.png)
![2021-11-24_03 09 53](https://user-images.githubusercontent.com/6895485/143324176-25e742d5-b87f-4652-b886-4aad5aea4acb.png)
For context of power creep.
