### ISSUE TITLE
Mod causing crash on initialization

### ISSUE THREAD

**Issue by McSquizzleswag** [P3pp3rF1y/Reliquary#538]
Your mod, along with ~~Astral Sorcery~~ and Simple Storage Network are causing a crash, I am telling the devs of the other mods of this issue too. My pack has the latest version of your mod
[latest.log](https://github.com/P3pp3rF1y/Reliquary/files/7699241/latest.log)

**Comment by P3pp3rF1y** [comment]
I will need more info on how to recreate your issue. I have all 3 mods running together without any issue. 
Also I don't see how this issue could happen unless some mod is trying to make these calls way too early in the load process before item handler capability gets a chance to load or is messed up in some other way and ends up being null.

**Comment by McSquizzleswag** [comment]
Download the ZF Community MC Pack from the Curseforge site, import it to your instance of the Curseforge app, update every mod, and try to launch it. The developer of Astral Sorcery told me their mod isn't part of the problem

**Comment by P3pp3rF1y** [comment]
I don't have time to debug different modpacks and their issues so I will need you to narrow this down to minimal set of mods that are still causing issues

**Comment by McSquizzleswag** [comment]
Your mod and Simple Storage Network are currently the two mods causing issues, but you won't see the issue unless _you have the pack_, the game launches just fine when it's the two mods on their own

**Comment by P3pp3rF1y** [comment]
exactly so it's another mod's interaction with these that's causing it and I will need to know which one otherwise I am not able to even comment on where is the default let alone fix if it's found out it's actually on Reliquary side. From all I have seen so far I don't think it's Reliquary's fault because based on what I can see and based on fact that it works otherwise something is either triggering these calls way too soon in the process or is messing with item handler capability making it null

**Comment by McSquizzleswag** [comment]
The only time these crashes would start to occur is when the latest version of Electrodynamics by Aurilisdev is present, whenever I remove that mod, along with its dependent mods or downgrade those mods the game launches as normal

**Comment by P3pp3rF1y** [comment]
yeah so this is an issue with electrodynamics, they have one issue open now for interaction with iron furnaces that is the same thing and a number closed for refined storage and simple storage networks where they basically say that they can't see electrodynamics in the stack trace but the only thing that connects those issues is that once you update to a certain version of electrodynamics all these mods crash and they and Reliquary are all big enough and in big modpacks that if these mods caused crashes otherwise we would be fixing them. 

From what I found in comments Darkere from refinedstorage commented that electrodynamics are trying to get tooltip of item way too soon in the load process.

**Comment by McSquizzleswag** [comment]
I see

**Comment by McSquizzleswag** [comment]
Thank you for your help, one of those closed issues is mine
