### ISSUE TITLE
If "chestLootEnabled = true" is set to false, mob drops do not drop from player death

### ISSUE THREAD

**Issue by zachsai** [P3pp3rF1y/Reliquary#566]
Title sums it up,
1.18.2, most recent version

**Comment by P3pp3rF1y** [comment]
well, based on the title I don't understand what is your exact issue. you mean you as a player die and no items drop? This setting has nothing to do with that, it's only used to add loot to chests if that setting is enabled so disabling it makes it not add reliquary chest loot. It can't remove player drops and is not even used during the actual game when the player inventory dropping code runs. So I will definitely need more info on what your issue is here.

**Comment by zachsai** [comment]
From player kill, my apologies

**Comment by P3pp3rF1y** [comment]
mob drops have separate config, just double checked that it's used properly. How many mobs have you actually killed? In 1.18 the chance was lowered in favor of using a new Severing enchantment. So unless you're saying you have killed hundreds and yet there was no drop this is likely just the fact that the chance is lower and you haven't killed big enough number.

**Comment by P3pp3rF1y** [comment]
Closing due to no further updates provided
