### ISSUE TITLE
[1.18.2] Game crashed when apothecary cauldron is placed near other block entities with Rubidium installed

### ISSUE THREAD

**Issue by yanang007** [P3pp3rF1y/Reliquary#578]
Game version: 1.18.2
Mod version: Reliquary 1.18.2-2.0.8.1139, Rubidium 0.5.2a

Step to reproduce:
1. Install both Reliquary and Rubidium.
2. Get into the game and place a cauldron and a mortar(any other block with block entity also works) near each other.
3. Game crashes.

Crash report:
https://paste.ubuntu.com/p/z4ZJp9ZnTH/

Possible cause is that rubidium's color blender [LinearColorBlender.java](https://github.com/Asek3/Rubidium/blob/e3aea98992e110b41ceed5ab128c81ff6fd98fa0/src/main/java/me/jellysquid/mods/sodium/client/model/quad/blender/LinearColorBlender.java#L53-L56) will call this [color sampler](https://github.com/P3pp3rF1y/Reliquary/blob/b018bf4f56ee2042e230517c9da68d6b1c188bdb/src/main/java/reliquary/client/init/ModBlockColors.java#L13-L22) on registered block and its neighbouring blocks. 
A possible workaround may be:
```
if (world.getBlockEntity(pos) instanceof ApothecaryCauldronBlockEntity cauldron) {
  if (cauldron.getLiquidLevel() > 0) {
    return cauldron.getColorMultiplier();
  }
}
```

**Comment by P3pp3rF1y** [comment]
I am sure you will have to complain to Rubidium about this. They somehow made it so that the incorrect block entity (mortar one) is passed to block color handler for cauldron. Nothing I can do about that. And I am not going to implement workarounds for something that should be working correctly on their side - there's a reason block color handler is being registered for a specific block and not in general for just about anything.

**Comment by yanang007** [comment]
Thanks for the reply! I see the point. It sure is a problem on Rubidium side.
