### ISSUE TITLE
Version 1.3.0.190 crashes Dedicated 1.8.9 Forge Server b1764 on startup

### ISSUE THREAD

**Issue by kreezxil** [P3pp3rF1y/Reliquary#58]
Issue: crashes dedicated 1.8.9 forge server b1764 on startup

crash report:
https://gist.github.com/f732b52edb5cbe0b98a7

fml server latest:
https://gist.github.com/1ceb9d0e1a89e72704e1

**Comment by P3pp3rF1y** [comment]
This is the same issue as #54. Some other mod is causing this to crash as this runs without issues on servers with blood magic. 
Would you be able to limit this down to what mod is causing it? I can then take a look at what exactly it is doing. But likely something really bad, because basically at that point in the code either Tome of Alkahestry is removed by some other mod or it is very strangely messing up with glowstone or redstone.
You can take a look at the list of mods in Pioneers modpack as that runs correctly so you should be able to limit it down to just additional mods you have in your pack.

**Comment by P3pp3rF1y** [comment]
What mod pack are you playing? I may try to debug it with those mods and see what breaks.

**Comment by kreezxil** [comment]
My own pack. The Extreme 1.8.9 Mega Pack found at http://kreezcraft.com as
a MultiMC download and also at Technic as a solder distribution
http://technicpack.net/modpack/extreme-189-mega-pack.815083

**Comment by P3pp3rF1y** [comment]
Closing, will release for 1.8.9 soon
