### ISSUE TITLE
[JEI] Mob Charms

### ISSUE THREAD

**Issue by hainkiwanki** [P3pp3rF1y/Reliquary#604]
I would like to hide all mob charms and their fragments, but neither JEI, nor KubeJS nor CraftTweaker seems to be able to hide them. Is there a config option I missed?

**Comment by malcolmriley** [comment]
I have just run into this issue myself.

The underlying cause seems to be an oversight with the way the mod registers the charm recipes with JEI.

The [JEI Plugin](https://github.com/P3pp3rF1y/Reliquary/blob/8020e80f94e24a5afc5ae670c90ccd9d0c2b4615/src/main/java/xreliquary/compat/jei/MobCharmRecipeMaker.java) for this mod simply adds the default recipe to JEI's display list, regardless of whether such a recipe exists.

Unfortunately this means that JEI will display these "false" recipes for the charms even if the actual recipes have been removed or altered - they will not work in the crafting table, but JEI will display them all the same; furthermore, under some circumstances these "false" recipes will be displayed and the "real" recipes will not.

@hainkiwanki: To answer your question there is also [no configuration available](https://github.com/P3pp3rF1y/Reliquary/blob/8020e80f94e24a5afc5ae670c90ccd9d0c2b4615/src/main/java/xreliquary/compat/jei/ReliquaryPlugin.java#L98) for this feature currently.

**Comment by hainkiwanki** [comment]
Oh, that's interesting. Good to know that. Thank you so much :D
