### ISSUE TITLE
Allow editing mob charm recipes.

### ISSUE THREAD

**Issue by genesy** [P3pp3rF1y/Reliquary#613]
Somehow add config for mob charms because it's not editable even with kubejs.

**Comment by malcolmriley** [comment]
I've just run into this issue myself (see commentary [here](https://github.com/P3pp3rF1y/Reliquary/issues/604#issuecomment-1430271540)).

The recipes are actually editable and recipe overrides do in fact work correctly, the problem seems to be that only the default recipes are registered with JEI and so only these "false" recipes are displayed even if they have been removed or overridden.
