### ISSUE TITLE
Crashed due to "concurrentmodificationexception" on latest patch

### ISSUE THREAD

**Issue by Hmloughin** [P3pp3rF1y/Reliquary#674]
Hello! 

I updated to the latest patch today. I don't have any reliquaries because this is a relatively new world so I haven't had a chance to interact with the mod yet. I was exploring trying to find a particular POI when my game froze and then crashed. I talked with someone in the Curseforge discord to make sure it wasn't anything I did wrong when I was updating a bunch of mods and they confirmed that Reliquary was the issue. 

Here's my latest log and crash report. Hope it helps!
[latest.log](https://github.com/P3pp3rF1y/Reliquary/files/14900545/latest.log)
[crash-2024-04-07_17.27.46-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/14900546/crash-2024-04-07_17.27.46-server.txt)

**Comment by P3pp3rF1y** [comment]
Seems like some mod is making it so that entities tick in parallel instead of one after each other and hence the crash. Potentially it could be lithium though I am not sure which one that is as you have a ton that modify vanilla code. I guess I will introduce concurrent collection there and hopefully that won't hurt performance much when this is done the usual way - one after each other.

**Comment by Hmloughin** [comment]
Thanks for the quick response. Yeah, I have a LOT of mods and used a base set of performance optimizers to support having a bunch of fun mods. There's conflict occasionally, but this time it was something I didn't know how to deal with without disabling the mode entirely. 

I'm sorry if this creates otherwise unnecessary problems for you.

**Comment by P3pp3rF1y** [comment]
Actually looks like this was related to triggering the code on client side as well when it wasn't required so in the latest release this was fixed to only trigger on server side
