### ISSUE TITLE
[Bug] 🐞 Crash - Possible Conflict With Touhou Little Maid Mod

### ISSUE THREAD

**Issue by serioos** [P3pp3rF1y/Reliquary#675]
I was getting attacked by one of those Touhou Little Maid fairies and she hit me a few times before the game crashed with reliquary as the cause. I think the fairy might have spawned with one of reliquary items on her?

I have a crash log here:

https://pastebin.com/cWtMBwGw

Here's my mod list:

https://pastebin.com/C1hB48AQ

Minecraft Forge 1.20.1 - 42.2.20

reliquary-1.20.1-2.0.40.1224.jar
touhoulittlemaid-1.20.1-release-1.1.8.jar

**Comment by P3pp3rF1y** [comment]
Nope this is a case of one of the ton of mods that you have there changing entity processing to be parallel which doesn't work with the logic I have that is made for single thread entity processing as is usual in MC. there's already a bug for that #674 . I will introduce a concurrent safe collection though I can't guarantee what else (what other mod) may break because of that other mod making this change.

**Comment by P3pp3rF1y** [comment]
Actually looks like this was related to triggering the code on client side as well when it wasn't required so in the latest release this was fixed to only trigger on server side
