### ISSUE TITLE
weird crash when placing logic gate from rf tools

### ISSUE THREAD

**Issue by Sailren** [P3pp3rF1y/Reliquary#96]
this null pointer happened when i tried to place the logic gate from rftools to get an and gate so i can test automatic start from bdews advanced generators steam turbine

http://paste.ubuntu.com/15859109/

**Comment by P3pp3rF1y** [comment]
That looks like you had ender staff in your inventory and perhaps shifted over it, because this is where it loads tooltip data.

Anyway it looks like I forgot to add a bit more safety checks in my code so I am going to include those just to be sure people don't crash like this even though just displaying tooltips works so there must a bit more happening here.
